[app]
name = "teleguard"

[services.teleguard]
type = "web"
instance_type = "nano"
regions = ["fra"]
env = [
  "PORT=8000"
]

[services.teleguard.build]
type = "buildpack"
buildpack = "heroku/python"

[services.teleguard.health_check]
http = { path = "/health" }

[services.teleguard.scaling]
min = 1
max = 1

[services.teleguard.ports]
- port = 8000
  protocol = "http"
  public = true