name: teleguard
services:
  - name: teleguard-bot
    type: web
    git:
      branch: test
      dockerfile: Dockerfile
    instance_type: nano
    regions:
      - fra
    ports:
      - port: 8080
        protocol: http
    health_check:
      http:
        path: /health
        port: 8080
      grace_period_seconds: 90
      interval_seconds: 30
      restart_limit: 3
    env:
      - key: API_ID
        scope: project
      - key: API_HASH
        scope: project
      - key: BOT_TOKEN
        scope: project
      - key: ADMIN_IDS
        scope: project
      - key: MONGO_URI
        scope: project
      - key: REDIS_URL
        scope: project
      - key: FERNET_KEY
        scope: project
      - key: PORT
        value: "8080"
      - key: ENVIRONMENT
        value: "production"
      - key: KOYEB_DEPLOYMENT
        value: "true"
