/* eslint-disable */
// This file is auto-generated by TanStack Router — do not edit manually.
// Run `npm run dev` or `npm run build` to regenerate.

import { createFileRoute, createRootRouteWithContext } from "@tanstack/react-router"

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexRoute } from "./routes/index"
import { Route as ChatChatIdRoute } from "./routes/chat.$chatId"

const rootRouteWithContext = rootRoute

export const routeTree = rootRouteWithContext.addChildren([
  IndexRoute,
  ChatChatIdRoute,
])

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    "/chat/$chatId": {
      id: "/chat/$chatId"
      path: "/chat/$chatId"
      fullPath: "/chat/$chatId"
      preLoaderRoute: typeof ChatChatIdRoute
      parentRoute: typeof rootRoute
    }
  }
}
