"""Protection Manager UI - Inline Menu Handlers"""

import logging
from datetime import datetime, timezone
from typing import Dict, Any

from telethon import events, Button
from ..services.protection_storage import ProtectionStorage

logger = logging.getLogger(__name__)

class ProtectionMenu:
    """Handle UI for the advanced Protection Manager"""

    def __init__(self, bot_manager):
        self.bot_manager = bot_manager
        self.bot = bot_manager.bot

    async def send_main_menu(self, event, user_id: int, edit: bool = False):
        """Display the premium protection dashboard"""
        settings = await ProtectionStorage.get_settings(user_id)
        stats = settings.get("stats", {})
        
        # Determine status indicators
        otp_status = "Enabled ✅" if settings.get("otp_destroyer_enabled") else "Disabled ❌"
        session_status = "Enabled ✅" if settings.get("session_destroyer_enabled") else "Disabled ❌"
        
        pause_until = settings.get("pause_until")
        if pause_until and pause_until > datetime.now(timezone.utc):
            remaining = (pause_until - datetime.now(timezone.utc)).total_seconds()
            status_text = f"Paused ⏳ ({int(remaining // 60)}m left)"
        else:
            status_text = "Active 🛡"

        trusted_count = len(settings.get("trusted_hashes", []))
        
        last_threat_time = stats.get("last_threat")
        if last_threat_time:
            diff = (datetime.now(timezone.utc) - last_threat_time.replace(tzinfo=timezone.utc)).total_seconds()
            if diff < 60: last_threat = "Just now"
            elif diff < 3600: last_threat = f"{int(diff // 60)}m ago"
            else: last_threat = f"{int(diff // 3600)}h ago"
        else:
            last_threat = "None detected"

        text = (
            "🛡 **TeleGuard Protection Manager**\n\n"
            f"**Status:** {status_text}\n\n"
            f"**OTP Destroyer:**\n{otp_status}\n\n"
            f"**Session Destroyer:**\n{session_status}\n\n"
            f"👤 **Trusted Sessions:** {trusted_count} Devices\n"
            f"⚠️ **Last Threat:** {last_threat}\n\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "💡 _Advanced protection is monitoring your accounts 24/7._"
        )

        buttons = [
            [
                Button.inline("🛡 OTP Settings", data="prot_otp_settings"),
                Button.inline("💻 Session Settings", data="prot_session_settings")
            ],
            [
                Button.inline("⏳ Pause Protection", data="prot_pause_menu"),
                Button.inline("🔓 Allow Next Login", data="prot_allow_next")
            ],
            [
                Button.inline("📊 Statistics", data="prot_stats"),
                Button.inline("📝 Logs", data="prot_logs")
            ],
            [
                Button.inline("🔄 Refresh", data="prot_refresh"),
                Button.inline("✖️ Close", data="close_menu")
            ]
        ]

        if edit:
            await event.edit(text, buttons=buttons)
        else:
            await event.respond(text, buttons=buttons)

    async def send_pause_menu(self, event, user_id: int):
        """Display pause duration options"""
        text = (
            "⏳ **Pause Protection**\n\n"
            "Temporarily disable all protection systems. "
            "Protection will auto-resume after the timer expires.\n\n"
            "⚠️ **Warning:** Your account will be vulnerable during this period."
        )
        
        buttons = [
            [Button.inline("5 Minutes", data="prot_pause_5"), Button.inline("30 Minutes", data="prot_pause_30")],
            [Button.inline("1 Hour", data="prot_pause_60"), Button.inline("24 Hours", data="prot_pause_1440")],
            [Button.inline("🔙 Back", data="prot_main")]
        ]
        
        await event.edit(text, buttons=buttons)

    async def send_stats(self, event, user_id: int):
        """Display protection statistics"""
        settings = await ProtectionStorage.get_settings(user_id)
        stats = settings.get("stats", {})
        
        text = (
            "📊 **Protection Statistics**\n\n"
            f"🔥 **OTP Destroyed:** {stats.get('otp_destroyed', 0)}\n"
            f"🚫 **Sessions Terminated:** {stats.get('sessions_destroyed', 0)}\n"
            f"📅 **System Active Since:** {settings.get('enabled_at').strftime('%Y-%m-%d')}\n"
            f"🛡 **Trust Score:** High ✅\n\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "Generated by TeleGuard Sentinel"
        )
        
        await event.edit(text, buttons=[[Button.inline("🔙 Back", data="prot_main")]])
